example_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views
import app.views
from chatbot.views import home, get_response
import accounts.views

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', app.views.a, name='a'),
    path('voca/', app.views.voca, name='voca'),
    path('signup/', accounts.views.signup, name='signup'),
    path('login/', accounts.views.login, name='login'),
    path('logout/', accounts.views.logout, name='logout'),
    path('search/', app.views.search, name='search'),
    path('voca_elementary/', app.views.voca_elementary,
         name='voca_elementary'),
    path('voca_high/', app.views.voca_high, name='voca_high'),
    path('voca_ma/', app.views.voca_ma, name='voca_ma'),
    path('voca_test/', app.views.voca_test, name='voca_test'),
    path('test_result/', app.views.test_result, name='test_result'),
    path('listen/', include('video.urls')),
    path('write/', app.views.write, name='write'),
    path('pronounce/', app.views.pronounce, name='pronounce'),
    path('evaluate/',app.views.evaluate, name='evaluate'),
    path('voca_cate/', app.views.voca_cate, name='voca_cate'),
    path('user_profile/', app.views.user_profile, name='user_profile'),
    path('ranking/', app.views.ranking, name='ranking'),
    path('de/', app.views.de, name='de'),
    path('chatbot/', home, name='chatbot'),
    path('get-response/', get_response),
    path('todo',include('todo.urls')),
    
]
if settings.DEBUG == True:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

todo/urls.py
from django.urls import path
from .views import IndexView, DetailView, DeleteView, UpdateView, CreateView

app_name = 'todo'

urlpatterns = [
    path('', IndexView.as_view(), name='todolist'),
    path('detail/<int:pk>/', DetailView.as_view(), name="todolist_detail"),
    path('delete/<int:pk>/', DeleteView.as_view(), name="todolist_delete"),
    path('update/<int:pk>/', UpdateView.as_view(), name='todolist_update'),

    path('create/', CreateView.as_view(), name='todolist_create'),
]

todo/models.py
from django.contrib.auth.models import User
from django.db import models
from datetime import date
import datetime


# Create your models here.


class TodoList(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=False, blank=False)
    name = models.CharField(max_length=40, verbose_name="할일제목")
    description = models.TextField(max_length=200, verbose_name="할일세부사항")
    date_created = models.DateField(auto_now_add=True, verbose_name="생성날짜")
    date_deadline = models.DateField(verbose_name="데드라인")

    def remaining_days(self):
        delta = self.date_deadline - date.today()
        days = delta.days
        return days

    def __str__(self):
        return f'{self.name} | {self.description} | {self.date_created} | 		  {self.date_deadline}'

todo/forms.py
from datetime import datetime

from django import forms
from django.core.exceptions import ValidationError

from todo.models import TodoList


class TodoCreateForm(forms.ModelForm):
    class Meta:
        model = TodoList
        fields = ['name', 'description', 'date_deadline']
    name = forms.CharField(
        max_length=20,
        widget=forms.TextInput(
            attrs={
                'class': 'input',
                'placeholder': '해야할일',
            }
        )
    )

    description = forms.CharField(
        max_length=200,
        widget=forms.Textarea(
            attrs={
                'class': 'textarea',
                'placeholder': '할일에 대한 디테일',
            }
        )
    )

    date_deadline = forms.DateField(
        widget=forms.DateInput(
            attrs={
                'id': 'datepicker',
                'placeholder': 'YYYY-MM-DD',
            }
        )
    )

    def clean(self):
        cleaned_data = super().clean()
        date_deadline = cleaned_data.get("date_deadline")

        if date_deadline < datetime.today().date():
            raise ValidationError(
                "데드라인이 잘못되었습니다"
            )
        return cleaned_data

todo/views.py
from datetime import date

from django.shortcuts import render, redirect
from django.urls import reverse_lazy

from .models import TodoList
from django.views import generic
from .forms import TodoCreateForm


# Create your views here. 


class IndexView(generic.ListView):
    context_object_name = 'to_do_list'

    def get_queryset(self):
        return TodoList.objects.filter(author=self.request.user)


class DetailView(generic.DetailView):
    contxt_object_name = 'todolist'

    def get_queryset(self):
        return TodoList.objects.filter(author=self.request.user)


class DeleteView(generic.DeleteView):
    success_url = reverse_lazy("todo:todolist")
    tempalte_name = 'todo/delete.html'

    def get_queryset(self):
        return TodoList.objects.filter(author=self.request.user)


class UpdateView(generic.UpdateView):
    fields = ['name', 'description', 'date_deadline']
    template_name = 'todo/create.html'
    success_url = reverse_lazy("todo:todolist")

    def get_queryset(self):
        return TodoList.objects.filter(author=self.request.user)


class CreateView(generic.CreateView):
    form_class = TodoCreateForm
    success_url = reverse_lazy("todo:todolist")
    template_name = "todo/create.html"

    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.author = self.request.user
        instance.save()
        return super().form_valid(form)

todo/templates/todo/create.html
{% extends 'todo_base.html' %}
{% block head %}
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<link rel="stylesheet" href="/resources/demos/style.css">
<link href="../static/img/favicon.ico" rel="shortcut icon" type="image/x-icon">
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script>
  $(function () {
    $("#datepicker").datepicker();
  });
</script>

{% endblock %}

{% block content %}
{% load static %}
<html>

<style>
  

  @font-face {
    font-family: 'Handon3gyeopsal600g';
    src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_seven@1.2/Handon3gyeopsal600g.woff') format('woff');
    font-weight: normal;
    font-style: normal;
  }

  

  .Handon3gyeopsal600g-font {
    font-family: 'Handon3gyeopsal600g', sans-serif;
    /* color: black; */
  }

  
</style>


<article class="message">

  <div class="message-header Handon3gyeopsal600g-font">
    <p>Todo List 추가</p>
    <button class="delete" aria-label="delete"></button>
  </div>
  <div class="message-body Handon3gyeopsal600g-font">
    새로운 투두 리스트를 추가해 보세요!
  </div>

</article>


<div class="columns is-centered Handon3gyeopsal600g-font">
  {{ form.non_field_errors }}
  <form action="" method="POST" enctype="multiplart/form-data" style="margin-top: 50px;">
    {% csrf_token %}
    {% for field in form %}

    {% if field.name == 'images' or field.name == 'files' %}

    {{ field.name }}
    <div class="file has-name Handon3gyeopsal600g-font" style="margin-top: 10px;">
      <label class="file-label Handon3gyeopsal600g-font">
        {{ field }}
        <span class="file-cta Handon3gyeopsal600g-font">
          <span class="file-icon Handon3gyeopsal600g-font">
            <i class="fas fa-upload Handon3gyeopsal600g-font"></i>
          </span>
          <span class="file-label Handon3gyeopsal600g-font">
            Choose {{ field.name }} to upload
          </span>
        </span>
        <span class="file-name Handon3gyeopsal600g-font">
          Upload your {{ field.name }} here
        </span>
      </label>


    </div>

    {% else %}

    <div class="field Handon3gyeopsal600g-font" style="margin-top: 10px;">
      {{ field.name }}
      <div class="control Handon3gyeopsal600g-font">
        {{ field }}
      </div>
    </div>
    {% endif %}
    {% endfor %}

    <div class="field is-grouped is-grouped-centered" style="margin-top: 30px;">
      <div class="control">
        <!-- <button class="button is-link">추가</button> -->
        <!-- <button class="button is-link is-inverted">추가</button> -->
        <button class="button is-light is-small Handon3gyeopsal600g-font">추가</button>

      </div>
      <div class="control">

        <!-- <button class="button is-danger is-light">취소</button> -->
        <!-- <a href="{{request.META.HTTP_REFERER}}">취소</a> -->
        <button class="button is-light is-small Handon3gyeopsal600g-font"><a href="javascript:history.back();">취소</a></button>

      </div>
    </div>
  </form>
</div>
{% endblock %}

todo/templates/todo/todo-lists.html
{% extends 'todo_base.html' %}

{% block title %}내가 할일 뭐지?{% endblock %}

{% block content %}
  
<ul>
{% for todo in to_do_list %}

<li>할일 제목 : {{ todo.name }}</li>


<li>생성 날짜 : {{ todo.date_created }}</li>

<li>데드라인 날짜 : {{ todo.date_deadline }}</li>

<li>남은 일수 : {{ todo.remaining_days }}</li>

{% endfor %}
</ul>

{% endblock content %}

todo/templates/todo/todolist_detail.html
{% extends 'todo_base.html' %}

{% block title %}할일 정보{% endblock %}

{% block content %}
{% load static %}
<html>

<style>
  @font-face {
    font-family: 'ghanachoco';
    src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_20-04@1.0/ghanachoco.woff') format('woff');
    font-weight: normal;
    font-style: normal;
  }

  @font-face {
    font-family: 'Handon3gyeopsal600g';
    src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_seven@1.2/Handon3gyeopsal600g.woff') format('woff');
    font-weight: normal;
    font-style: normal;
  }

  .ghanachoco-font {
    font-family: 'ghanachoco', sans-serif;
    color: black;
  }

  .Handon3gyeopsal600g-font {
    font-family: 'Handon3gyeopsal600g', sans-serif;
    color: black;
  }

  .half-highlight {
    background: linear-gradient(180deg, rgba(255, 255, 255, 0) 50%, #FFD0AE 50%);
  }

  .spread-underline {
    color: #333;
    text-decoration: none;
    display: inline-block;
    padding: 15px 0;
    position: relative;
  }

  .spread-underline:after {
    background: none repeat scroll 0 0 transparent;
    bottom: 0;
    content: "";
    display: block;
    height: 2px;
    left: 50%;
    position: absolute;
    background: #ffb000;
    transition: width 0.3s ease 0s, left 0.3s ease 0s;
    width: 0;
  }

  .spread-underline:hover:after {
    width: 100%;
    left: 0;
  }
</style>

<head>
  <title>투두 리스트</title>
  <meta charset="utf-8" />
  <link href="../static/img/favicon.ico" rel="shortcut icon" type="image/x-icon">
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <link rel="stylesheet" href="{% static 'css/main.css' %}">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
    crossorigin="anonymous"></script>
  <style type="text/css">
    a {
      text-decoration: none
    }
  </style>
</head>

<body>

  <div class="fixed-top Handon3gyeopsal600g-font">
    <div class="collapse" id="navbarToggleExternalContent">
      <div class="bg-dark p-4" style="color: white;">
        {%if user.is_authenticated%}
        <a href="{%url 'a'%}">
          <h5 class="text-white h3">{{user.profile.nickname}}님 반갑습니다!</h5>
        </a>
        <span class="text-muted">
          <form>ㅤ
            <a href="{%url 'user_profile'%}" style="color: white;">내정보 </a>
            <a href="{%url 'ranking'%}" style="color: white;">ㅤㅤ현재 순위ㅤ</a>
            {%csrf_token%}
            <form action="{%url 'logout'%}" method="POST">
              <input type="submit" value="로그아웃" style="font-size: 0.8rem;">
            </form>
            {%else%}
            <a href="{%url 'signup'%}">회원가입</a>
            <a href="{%url 'login'%}">로그인</a>
            {%endif%}
          </form>
        </span>
      </div>
    </div>
    <nav class="navbar navbar-dark bg-light">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggleExternalContent"
        aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="nav-link spread-underline" href="{%url 'voca_cate'%}" style="color:black; font-size:1.1rem;">단어장</a>
      <a class="nav-link spread-underline" href="{%url 'voca_test'%}" style="color:black; font-size:1.1rem;">단어테스트</a>
      <a class="nav-link spread-underline" href="{%url 'listen'%}" style="color:black; font-size:1.1rem;">영어듣기</a>
      <a class="nav-link spread-underline" href="{%url 'pronounce'%}" style="color:black; font-size:1.1rem;">발음연습</a>
      <a class="nav-link spread-underline" href="{%url 'chatbot'%}" style="color:black; font-size:1.1rem;">챗봇</a>
      <a class="nav-link spread-underline" href="{%url 'write'%}" style="color:black; font-size:1.1rem;">손글씨 쓰기</a>
      <a class="nav-link spread-underline" href="{%url 'todo:todolist'%}"
        style="color:black; font-size:1.1rem;">투두리스트</a>
    </nav>
  </div>
  <section id="three" class="wrapper">
    <div class="content container">
      <header class="page-header" style="overflow: auto;">
        <center>
          <br><br>
          <h1 class="ghanachoco-font" style="display: inline; font-size: 3.3rem">To-do List</h1>

        </center>
        <!-- <a class="btn btn-default" href="/listen/new" style="float: right;">New Video</a> -->
      </header>

<div class="rows">

    
    <div class="card row">
        <!-- <header class="card-header"> -->
          <div class="card-header Handon3gyeopsal600g-font">
            ● 할일 : {{ todolist.name }}
          </div>
          <!-- <a href="#" class="card-header-icon" aria-label="more options">
            <span class="icon">
              <i class="fas fa-angle-down" aria-hidden="true"></i>
            </span>
          </a> -->
        </header>
        <div class="card-content Handon3gyeopsal600g-font">
          <div class="content Handon3gyeopsal600g-font">
            <br>
            해야 할일 : {{ todolist.description }}
            <br>
            <hr>
            생성 날짜 : {{ todolist.date_created }}
            <br>
            데드 라인 : {{ todolist.date_deadline }}
            <hr>
            남은 일수 : {{ todolist.remaining_days }}
            <br>
            <br>
          </div>
        </div>
        <footer class="card-footer">
            <a href="{% url 'todo:todolist' %}" class="card-footer-item"><button class="button is-dark is-fullwidth Handon3gyeopsal600g-font">뒤로가기</button></a>
            <a href="{% url 'todo:todolist_update' todolist.pk %}" class="card-footer-item"><button class="button is-dark is-fullwidth Handon3gyeopsal600g-font">수정하기</button></a>
            <a href="{% url 'todo:todolist_delete' todolist.pk %}" class="card-footer-item"><button class="button is-dark is-fullwidth Handon3gyeopsal600g-font">완료</button></a>
          </footer>
      </div>
    
{% endblock content %}

todo/templates/todo/todolist_list.html
{% load static %}
<html>

<style>
  @font-face {
    font-family: 'ghanachoco';
    src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_20-04@1.0/ghanachoco.woff') format('woff');
    font-weight: normal;
    font-style: normal;
  }

  @font-face {
    font-family: 'Handon3gyeopsal600g';
    src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_seven@1.2/Handon3gyeopsal600g.woff') format('woff');
    font-weight: normal;
    font-style: normal;
  }

  .ghanachoco-font {
    font-family: 'ghanachoco', sans-serif;
    color: black;
  }

  .Handon3gyeopsal600g-font {
    font-family: 'Handon3gyeopsal600g', sans-serif;
    color: black;
  }

  .half-highlight {
    background: linear-gradient(180deg, rgba(255, 255, 255, 0) 50%, #FFD0AE 50%);
  }

  .spread-underline {
    color: #333;
    text-decoration: none;
    display: inline-block;
    padding: 15px 0;
    position: relative;
  }

  .spread-underline:after {
    background: none repeat scroll 0 0 transparent;
    bottom: 0;
    content: "";
    display: block;
    height: 2px;
    left: 50%;
    position: absolute;
    background: #ffb000;
    transition: width 0.3s ease 0s, left 0.3s ease 0s;
    width: 0;
  }

  .spread-underline:hover:after {
    width: 100%;
    left: 0;
  }
</style>

<head>
  <title>투두 리스트</title>
  <meta charset="utf-8" />
  <link href="../static/img/favicon.ico" rel="shortcut icon" type="image/x-icon">
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <link rel="stylesheet" href="{% static 'css/main.css' %}">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
    crossorigin="anonymous"></script>
  <style type="text/css">
    a {
      text-decoration: none
    }
  </style>
</head>

<body>

  <div class="fixed-top Handon3gyeopsal600g-font">
    <div class="collapse" id="navbarToggleExternalContent">
      <div class="bg-dark p-4" style="color: white;">
        {%if user.is_authenticated%}
        <a href="{%url 'a'%}">
          <h5 class="text-white h3">{{user.profile.nickname}}님 반갑습니다!</h5>
        </a>
        <span class="text-muted">
          <form>ㅤ
            <a href="{%url 'user_profile'%}" style="color: white;">내정보 </a>
            <a href="{%url 'ranking'%}" style="color: white;">ㅤㅤ현재 순위ㅤ</a>
            {%csrf_token%}
            <form action="{%url 'logout'%}" method="POST">
              <input type="submit" value="로그아웃" style="font-size: 0.8rem;">
            </form>
            {%else%}
            <a href="{%url 'signup'%}">회원가입</a>
            <a href="{%url 'login'%}">로그인</a>
            {%endif%}
          </form>
        </span>
      </div>
    </div>
    <nav class="navbar navbar-dark bg-light">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggleExternalContent"
        aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="nav-link spread-underline" href="{%url 'voca_cate'%}" style="color:black; font-size:1.1rem;">단어장</a>
      <a class="nav-link spread-underline" href="{%url 'voca_test'%}" style="color:black; font-size:1.1rem;">단어테스트</a>
      <a class="nav-link spread-underline" href="{%url 'listen'%}" style="color:black; font-size:1.1rem;">영어듣기</a>
      <a class="nav-link spread-underline" href="{%url 'pronounce'%}" style="color:black; font-size:1.1rem;">발음연습</a>
      <a class="nav-link spread-underline" href="{%url 'chatbot'%}" style="color:black; font-size:1.1rem;">챗봇</a>
      <a class="nav-link spread-underline" href="{%url 'write'%}" style="color:black; font-size:1.1rem;">손글씨 쓰기</a>
      <a class="nav-link spread-underline" href="{%url 'todo:todolist'%}"
        style="color:black; font-size:1.1rem;">투두리스트</a>
    </nav>
  </div>

  <!-- Three -->
  <section id="three" class="wrapper">
    <div class="content container">
      <header class="page-header" style="overflow: auto;">
        <center>
          <br><br>
          <h1 class="ghanachoco-font" style="display: inline; font-size: 3.3rem">To-do List</h1>

        </center>
        <!-- <a class="btn btn-default" href="/listen/new" style="float: right;">New Video</a> -->
      </header>
      {% block content %}

      <a href="{% url 'todo:todolist_create' %}">
        <br>
        <button class="button is-info is-rounded is-fullwidth Handon3gyeopsal600g-font">할일 추가하기</button>
        <br>
        <br>
      </a>


      <div class="rows">
        {% for todo in to_do_list %}

        <div class="card row">
          <!-- <header class="card-header">  -->
          <!-- <div class="card-header-title"> -->
          <div class="card-header Handon3gyeopsal600g-font">
            ● 할일 : {{ todo.name }}
          </div>
          <!-- </div>   -->

          <!-- </header>  -->

          <div class="card-content Handon3gyeopsal600g-font">
            <div class="content Handon3gyeopsal600g-font">
              <br>
              해야 할일 : {{ todo.description|truncatechars:30 }}
              <br>
              <hr>
              생성 날짜 : {{ todo.date_created }}
              <br>
              데드 라인 : {{ todo.date_deadline }}
              <hr>
              남은 일수 : {{ todo.remaining_days }}
              <br>
              <br>
            </div>
          </div>
          <footer class="card-footer">
            <a href="{% url 'todo:todolist_detail' todo.id %}" class="card-footer-item"><button
                class="button is-primary is-fullwidth Handon3gyeopsal600g-font">더보기</button></a>
            <a href="{% url 'todo:todolist_update' todo.id %}" class="card-footer-item"><button
                class="button is-warning is-fullwidth Handon3gyeopsal600g-font">수정하기</button></a>
            <a href="{% url 'todo:todolist_delete' todo.id %}" class="card-footer-item"><button
                class="button is-danger is-fullwidth Handon3gyeopsal600g-font">완료</button></a>
          </footer>

        </div>
        <hr>
        {% endfor %}

      </div>
      {% endblock content %}

  </section>


  <!-- Footer -->
  <footer id="footer">
    <div class="inner">
      <div class="flex">
        <div class="copyright">
          &copy; Untitled. Design: <a href="https://templated.co">TEMPLATED</a>. Images: <a
            href="https://unsplash.com">Unsplash</a>.
        </div>
        <ul class="icons">
          <li> <a href="http://cse.yu.ac.kr/main.php"><img src="{% static 'img/yu.png' %}" width="200px;"></a>
          </li>
        </ul>
      </div>
    </div>
  </footer>

  <!-- Scripts -->
  <script src="../static/js/jquery.min.js"></script>
  <script src="../static/js/skel.min.js"></script>
  <script src="../static/js/util.js"></script>
  <script src="../static/js/main.js"></script>

</body>

</html>