example_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views
import app.views
from chatbot.views import home, get_response
import accounts.views

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', app.views.a, name='a'),
    path('voca/', app.views.voca, name='voca'),
    path('signup/', accounts.views.signup, name='signup'),
    path('login/', accounts.views.login, name='login'),
    path('logout/', accounts.views.logout, name='logout'),
    path('search/', app.views.search, name='search'),
    path('voca_elementary/', app.views.voca_elementary,
         name='voca_elementary'),
    path('voca_high/', app.views.voca_high, name='voca_high'),
    path('voca_ma/', app.views.voca_ma, name='voca_ma'),
    path('voca_test/', app.views.voca_test, name='voca_test'),
    path('test_result/', app.views.test_result, name='test_result'),
    path('listen/', include('video.urls')),
    path('write/', app.views.write, name='write'),
    path('pronounce/', app.views.pronounce, name='pronounce'),
    path('evaluate/',app.views.evaluate, name='evaluate'),
    path('voca_cate/', app.views.voca_cate, name='voca_cate'),
    path('user_profile/', app.views.user_profile, name='user_profile'),
    path('ranking/', app.views.ranking, name='ranking'),
    path('de/', app.views.de, name='de'),
    path('chatbot/', home, name='chatbot'),
    path('get-response/', get_response),
    path('todo',include('todo.urls')),
    
]
if settings.DEBUG == True:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

todo/urls.py
from django.urls import path
from .views import IndexView, DetailView, DeleteView, UpdateView, CreateView

app_name = 'todo'

urlpatterns = [
    path('', IndexView.as_view(), name='todolist'),
    path('detail/<int:pk>/', DetailView.as_view(), name="todolist_detail"),
    path('delete/<int:pk>/', DeleteView.as_view(), name="todolist_delete"),
    path('update/<int:pk>/', UpdateView.as_view(), name='todolist_update'),

    path('create/', CreateView.as_view(), name='todolist_create'),
]

app/templates/a.html
{% load static %}
<html>

<style>
    @font-face {
        font-family: 'ghanachoco';
        src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_20-04@1.0/ghanachoco.woff') format('woff');
        font-weight: normal;
        font-style: normal;
    }

    @font-face {
        font-family: 'Handon3gyeopsal600g';
        src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_seven@1.2/Handon3gyeopsal600g.woff') format('woff');
        font-weight: normal;
        font-style: normal;
    }

    .ghanachoco-font {
        font-family: 'ghanachoco', sans-serif;
        color: black;
    }

    .Handon3gyeopsal600g-font {
        font-family: 'Handon3gyeopsal600g', sans-serif;
        color: black;
    }

    .half-highlight {
        background: linear-gradient(180deg, rgba(255, 255, 255, 0) 50%, #FFD0AE 50%);
    }

    .spread-underline {
        color: #333;
        text-decoration: none;
        display: inline-block;
        padding: 15px 0;
        position: relative;
    }

    .spread-underline:after {
        background: none repeat scroll 0 0 transparent;
        bottom: 0;
        content: "";
        display: block;
        height: 2px;
        left: 50%;
        position: absolute;
        background: #ffb000;
        transition: width 0.3s ease 0s, left 0.3s ease 0s;
        width: 0;
    }

    .spread-underline:hover:after {
        width: 100%;
        left: 0;
    }
</style>

<head>
    <title>머핀의 법칙 - AI 기반 영어 교육</title>
    <meta charset="utf-8" />
    <link href="../static/img/core-img/favicon.ico" rel="shortcut icon" type="image/x-icon">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
        crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
    <style type="text/css">
        a {
            text-decoration: none
        }
    </style>

</head>

<body>
    <div class="fixed-top Handon3gyeopsal600g-font">
        <div class="collapse" id="navbarToggleExternalContent">
            <div class="bg-dark p-4" style="color: white;">
                {%if user.is_authenticated%}
                <a href="{%url 'a'%}">
                    <h5 class="text-white h3">{{user.profile.nickname}}님 반갑습니다!</h5>
                </a>
                <span class=" text-muted">
                    <form>ㅤ
                        <a href="{%url 'user_profile'%}" style="color: white;">내정보 </a>
                        <a href="{%url 'ranking'%}" style="color: white;">ㅤㅤ현재 순위ㅤ</a>
                        <!-- <form action="{%url 'logout'%}" method="POST">-->
                        {%csrf_token%}
                        <button type="button" class="btn btn-primary btn-sm"><a href="{%url 'logout'%}"
                                style="color: white;">로그아웃하기</a>
                        </button>
                        <!-- <input type="submit" value="로그아웃" style="font-size: 0.8rem;"> -->
                    </form>
                    {%else%}
                    <a href="{%url 'signup'%}" style="color: white;">회원가입ㅤ</a>
                    <a href="{%url 'login'%}" style="color: white;">로그인</a>
                    {%endif%}
                    </form>
                </span>
            </div>
        </div>
        <nav class="navbar navbar-dark bg-light">
            <button class="navbar-toggler" type="button" data-toggle="collapse"
                data-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent"
                aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <a class="nav-link spread-underline" href="{%url 'voca_cate'%}"
                style="color:black; font-size:1.1rem;">단어장</a>
            <a class="nav-link spread-underline" href="{%url 'voca_test'%}"
                style="color:black; font-size:1.1rem;">단어테스트</a>
            <a class="nav-link spread-underline" href="{%url 'listen'%}" style="color:black; font-size:1.1rem;">영어듣기</a>
            <a class="nav-link spread-underline" href="{%url 'pronounce'%}"
                style="color:black; font-size:1.1rem;">발음연습</a>
            <a class="nav-link spread-underline" href="{%url 'chatbot'%}" style="color:black; font-size:1.1rem;">챗봇</a>
            <a class="nav-link spread-underline" href="{%url 'write'%}" style="color:black; font-size:1.1rem;">손글씨
                쓰기</a>
            <a class="nav-link spread-underline" href="{%url 'todo:todolist'%}"
                style="color:black; font-size:1.1rem;">투두리스트</a>
        </nav>
    </div>

    <!-- Banner -->
    <section id="banner">
        <h1 style="font-size: 4.5rem; text-shadow: -0.5px 0 rgb(110, 110, 110),
        0 0.5px  rgb(110, 110, 110),
        0.5px 0 rgb(110, 110, 110),
        0 -0.5px  rgb(110, 110, 110);" class="ghanachoco-font">머핀의 법칙</h1>
        <p class="Handon3gyeopsal600g-font" style="font-size: 1.1rem; ">AI 기반 영어 교육 웹 서비스</p>
    </section>

    <!-- One -->
    <section id="one" class="wrapper">
        <div class="inner Handon3gyeopsal600g-font">
            <!-- <div class="flex flex-3"> -->
            <article>
                <center>
                    <header>
                        <h1 style="font-weight: bold; font-size: 1.5rem;">오늘의 표현</h1>
                    </header>
                    <p style="font-size: 1.3rem;">{{todays.today_word}} {{todays.today_mean}}</p>
                </center>
            </article>
            <!-- </div> -->
        </div>
    </section>

    <!-- Two -->
    <section id="two" class="wrapper style1 special">
        <div class="inner Handon3gyeopsal600g-font">
            <header>
                <h2>팀원소개</h2>
                <p></p>
            </header>
            <div class="flex flex-4">
                <div class="box person">
                    <div class="image round">
                        <img src="{% static 'img/face1.jpg' %}" alt="Person 1" />
                    </div>
                    <h3>조은지</h3>
                    <p>21611771 <br>조장</p>
                </div>
                <div class="box person">
                    <div class="image round">
                        <img src="{% static 'img/faceee.jpg' %}" alt="Person 2" />
                    </div>
                    <h3>전상현</h3>
                    <p>21411895 <br>조원</p>
                </div>
                <div class="box person">
                    <div class="image round">
                        <img src="{% static 'img/4.jpg' %}" alt="Person 3" />
                    </div>
                    <h3>박수민</h3>
                    <p>21611730 <br>조원</p>
                </div>
                <div class="box person">
                    <div class="image round">
                        <img src="{% static 'img/2.jpg' %}" alt="Person 4" />
                    </div>
                    <h3>정승연</h3>
                    <p>21611768 <br>조원</p>
                </div>
                <div class="box person">
                    <div class="image round">
                        <img src="{% static 'img/3.png' %}" alt="Person 5" />
                    </div>
                    <h3>최아현</h3>
                    <p>21611778 <br>조원</p>
                </div>
            </div>
        </div>
    </section>

    <!-- Three
    <section id="three" class="wrapper special">
        <div class="inner">
            <header class="align-center">
                <h2>Nunc Dignissim</h2>
                <p>Aliquam erat volutpat nam dui </p>
            </header>
            <div class="flex flex-2">
                <article>
                    <div class="image fit">
                        <img src="images/pic01.jpg" alt="Pic 01" />
                    </div>
                    <header>
                        <h3>Praesent placerat magna</h3>
                    </header>
                    <p>Praesent dapibus, neque id cursus faucibus, tortor neque egestas augue, eu vulputate magna eros
                        eu erat. Aliquam erat volutpat. Nam dui mi, tincidunt quis, accumsan porttitor lorem ipsum.</p>
                    <footer>
                        <a href="#" class="button special">More</a>
                    </footer>
                </article>
                <article>
                    <div class="image fit">
                        <img src="images/pic02.jpg" alt="Pic 02" />
                    </div>
                    <header>
                        <h3>Fusce pellentesque tempus</h3>
                    </header>
                    <p>Sed adipiscing ornare risus. Morbi est est, blandit sit amet, sagittis vel, euismod vel, velit.
                        Pellentesque egestas sem. Suspendisse commodo ullamcorper magna non comodo sodales tempus.</p>
                    <footer>
                        <a href="#" class="button special">More</a>
                    </footer>
                </article>
            </div>
        </div>
    </section> -->

    <!-- Footer -->
    <footer id="footer">
        <div class="inner">
            <div class="flex">
                <div class="copyright">
                    &copy; Untitled. Design: <a href="https://templated.co">TEMPLATED</a>. Images: <a
                        href="https://unsplash.com">Unsplash</a>.
                </div>
                <ul class="icons">
                    <li> <a href="http://cse.yu.ac.kr/main.php"><img src="{% static 'img/yu.png' %}" width="200px;"></a>
                    </li>
                </ul>
            </div>
        </div>
    </footer>

    <!-- Scripts -->
    <!-- <script src="assets/js/jquery.min.js"></script>
    <script src="assets/js/skel.min.js"></script>
    <script src="assets/js/util.js"></script> -->
    <script src="{% static 'js/main.js' %}"></script>

</body>

</html>

app/templates/index.html
<!-- CSS -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
    integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

<!-- jQuery and JS bundle w/ Popper.js -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
    crossorigin="anonymous"></script>

<style>
    @font-face {
        font-family: 'MaplestoryOTFBold';
        src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_20-04@2.1/MaplestoryOTFBold.woff') format('woff');
        font-weight: normal;
        font-style: normal;
    }

    .maple-font {
        font-family: 'MaplestoryOTFBold', sans-serif;
        color: black;
    }
</style>



<center style="font-size: 1rem;" class="maple-font">
    <br>
    <h1>머핀</h1>
    <br>
    <br>
</center>
{%if user.is_authenticated%}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item active" aria-current="page"><a href="{%url 'voca_cate'%}">단어장</a>
        <li class="breadcrumb-item active" aria-current="page"><a href="{%url 'voca_test'%}">단어 테스트</a>
        <li class="breadcrumb-item active" aria-current="page"><a href="{%url 'listen'%}">영어듣기</a>
        <li class="breadcrumb-item active" aria-current="page"><a href="{%url 'write'%}">손글씨 쓰기</a>
        <li class="breadcrumb-item active" aria-current="page"><a href="{%url 'pronounce'%}">발음 연습</a>
        <li class="breadcrumb-item active" aria-current="page"><a href="{%url 'chatbot'%}">챗봇</a>
        <li class="breadcrumb-item active" aria-current="page"><a href="{%url 'de'%}">de</a>
        <li class="breadcrumb-item active" aria-current="page"><a href="{%url 'a'%}">a</a>
        <li class="breadcrumb-item active" aria-current="page"><a href="{%url 'todo:todolist'%}">투두리스트</a>
        
        </li>
    </ol>
    {%else%}
    <div>로그인 하지 않으면 메뉴 안보임</div>
    {%endif%}

</nav>
<div style="float: right;">
    {%if user.is_authenticated%}
    <div style="font-size: 1.1rem;">
        {{user.profile.nickname}}님ㅤ
        <form action="{%url 'logout'%}" method="POST" style="float: right; font-size: 1.1rem;">
            {%csrf_token%}
            <input type="submit" value="로그아웃" style="font-size: 1.0rem;">
        </form>
        <a href="{%url 'user_profile'%}">내정보 </a>
        <a href="{%url 'ranking'%}">현재 순위 </a>
    </div>
    {%else%}
    <a href="{%url 'signup'%}">회원가입</a>
    <a href="{%url 'login'%}">로그인</a>
    {%endif%}
</div>
<br>
<br>
<br>
<center>
    <div style="border:1px solid; padding:15px; width: 60rem;">
        <h3 class="maple-font">오늘의 표현</h3> {{todays.today_word}} {{todays.today_mean}}
    </div>
</center>

app/templates/pronounce.html
{% load static %}
<!DOCTYPE html>
<html lang="en-us">

<style>
  @font-face {
    font-family: 'ghanachoco';
    src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_20-04@1.0/ghanachoco.woff') format('woff');
    font-weight: normal;
    font-style: normal;
  }

  @font-face {
    font-family: 'Handon3gyeopsal600g';
    src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_seven@1.2/Handon3gyeopsal600g.woff') format('woff');
    font-weight: normal;
    font-style: normal;
  }

  .ghanachoco-font {
    font-family: 'ghanachoco', sans-serif;
    color: black;
  }

  .Handon3gyeopsal600g-font {
    font-family: 'Handon3gyeopsal600g', sans-serif;
    color: black;
  }

  .half-highlight {
    background: linear-gradient(180deg, rgba(255, 255, 255, 0) 50%, #FFD0AE 50%);
  }

  .spread-underline {
    color: #333;
    text-decoration: none;
    display: inline-block;
    padding: 15px 0;
    position: relative;
  }

  .spread-underline:after {
    background: none repeat scroll 0 0 transparent;
    bottom: 0;
    content: "";
    display: block;
    height: 2px;
    left: 50%;
    position: absolute;
    background: #ffb000;
    transition: width 0.3s ease 0s, left 0.3s ease 0s;
    width: 0;
  }

  .spread-underline:hover:after {
    width: 100%;
    left: 0;
  }
</style>

<head>
  <title>발음 연습</title>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">

  <link href="../static/img/core-img/favicon.ico" rel="shortcut icon" type="image/x-icon">
  <link href="../static/css/record.css?after" rel="stylesheet" type="text/css">

  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
    crossorigin="anonymous"></script>

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  <link rel="stylesheet" href="{% static 'css/main.css' %}" />
  <style type="text/css">
    a {
      text-decoration: none
    }
  </style>

</head>

<body>
  <div class="fixed-top Handon3gyeopsal600g-font">
    <div class="collapse" id="navbarToggleExternalContent">
      <div class="bg-dark p-4" style="color: white;">
        {%if user.is_authenticated%}
        <a href="{%url 'a'%}">
          <h5 class="text-white h3">{{user.profile.nickname}}님 반갑습니다!</h5>
        </a>
        <span class="text-muted">
          <form>ㅤ
            <a href="{%url 'user_profile'%}" style="color: white;">내정보 </a>
            <a href="{%url 'ranking'%}" style="color: white;">ㅤㅤ현재 순위ㅤ</a>
            {%csrf_token%}
            <form action="{%url 'logout'%}" method="POST">
              <input type="submit" value="로그아웃" style="font-size: 0.8rem;">
            </form>
            {%else%}
            <a href="{%url 'signup'%}">회원가입</a>
            <a href="{%url 'login'%}">로그인</a>
            {%endif%}
          </form>
        </span>
      </div>
    </div>
    <nav class="navbar navbar-dark bg-light">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggleExternalContent"
        aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="nav-link spread-underline" href="{%url 'voca_cate'%}" style="color:black; font-size:1.1rem;">단어장</a>
      <a class="nav-link spread-underline" href="{%url 'voca_test'%}" style="color:black; font-size:1.1rem;">단어테스트</a>
      <a class="nav-link spread-underline" href="{%url 'listen'%}" style="color:black; font-size:1.1rem;">영어듣기</a>
      <a class="nav-link spread-underline" href="{%url 'pronounce'%}" style="color:black; font-size:1.1rem;">발음연습</a>
      <a class="nav-link spread-underline" href="{%url 'chatbot'%}" style="color:black; font-size:1.1rem;">챗봇</a>
      <a class="nav-link spread-underline" href="{%url 'write'%}" style="color:black; font-size:1.1rem;">손글씨
        쓰기</a>
      <a class="nav-link spread-underline" href="{%url 'todo:todolist'%}"
        style="color:black; font-size:1.1rem;">투두리스트</a>
    </nav>
  </div>


  <div class="wrapper">
    <br>
    <br> <br>
    <br>
    <header>
      <h1>발음 연습</h1>
    </header>
    <br>
    <br>
    <section class="main-controls">
      <canvas class="visualizer" height="60px"></canvas>
      <div id="buttons">
        <button class="record">Record</button>
        <button class="stop">Stop</button>
      </div>
    </section>

    <section class="sound-clips">


    </section>

  </div>

  <label for="toggle">❔</label>
  <input type="checkbox" id="toggle">
  <aside>
    <h2>Information</h2>

    <p>Web dictaphone is built using <a
        href="https://developer.mozilla.org/en-US/docs/Web/API/Navigator.getUserMedia">getUserMedia</a> and the <a
        href="https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder_API">MediaRecorder API</a>, which provides
      an easier way to capture Media streams.</p>

    <p>Icon courtesy of <a href="http://findicons.com/search/microphone">Find Icons</a>. Thanks to <a
        href="http://soledadpenades.com/">Sole</a> for the Oscilloscope code!</p>
  </aside>
  {% csrf_token %}
  <script>const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;</script>
  <script src="http://code.jquery.com/jquery-latest.js"></script>
  <script src="../static/js/record.js?after"></script>
  <script src="../static/js/RecordRTC.js"></script>

  <footer id="footer">
    <div class="inner">
      <div class="flex">
        <div class="copyright">
          &copy; Untitled. Design: <a href="https://templated.co">TEMPLATED</a>. Images: <a
            href="https://unsplash.com">Unsplash</a>.
        </div>
        <ul class="icons">
          <li> <a href="http://cse.yu.ac.kr/main.php"><img src="{% static 'img/yu.png' %}" width="200px;"></a>
          </li>
        </ul>
      </div>
    </div>
  </footer>

  <!-- Scripts -->
  <script src="../static/js/jquery.min.js"></script>
  <script src="../static/js/skel.min.js"></script>
  <script src="../static/js/util.js"></script>
  <script src="../static/js/main.js"></script>


</body>

</html>